from tkinter import *


def eng_main():
    root = Tk()
    root.geometry('600x800')
    root.title('Mad Libs Game')
    root.resizable(False, False)
    root.configure(bg='lightblue')
    Label(root, text='Mad Libs Game \n Enjoy it!', font='arial 20 bold', bg='lightblue').pack()
    Label(root, text='Choose a story :', font='arial 15 bold', bg='lightblue').place(x=208, y=80)


    def madlib1():
        def finish_madlib(tl: Toplevel, adjective1, noun1, adjective2, noun2, adjective3, noun3, adjective4, noun4, adjective5, noun5, adjective6, noun6, adjective7, adjective8):
            text = f'''Today, I went to the {adjective1} {noun1} park with my {adjective2} {noun2}. We brought along some {adjective3} {noun3} and a{adjective4} {noun4} to play with. As we were playing, a {adjective5} {noun5} ran by and stole our {adjective6} {noun6}! We chased after it, but it was too {adjective7} to catch. Despite the mishap, we had a {adjective8} time at the park and can't wait to go back again.'''
            Label(tl, text='The story:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=480)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=480)

        top = Toplevel(bg='lightblue')
        top.title("The robbery")
        top.geometry('600x600')
        top.resizable(False, False)

        Label(top, text='The robbery - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)
        
        adjective1 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 60) 
        noun1 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 90)
        adjective2 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 120)
        noun2 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 150)
        adjective3 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 180)
        noun3 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 210)
        adjective4 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 240)
        noun4 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 270)
        adjective5 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 300)
        noun5 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 330)
        adjective6 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 360)
        noun6 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 390)
        adjective7 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 420)
        adjective8 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 450) 
        
        adjective1_input_area = Entry(top, width = 30)
        adjective1_input_area.place(x = 210, y = 60) 
        noun1_entry_area = Entry(top, width = 30)
        noun1_entry_area.place(x = 210, y = 90)
        adjective2_input_area = Entry(top, width = 30)
        adjective2_input_area.place(x = 210, y = 120)
        noun2_entry_area = Entry(top, width = 30)
        noun2_entry_area.place(x = 210, y = 150)
        adjective3_input_area = Entry(top, width = 30)
        adjective3_input_area.place(x = 210, y = 180)
        noun3_entry_area = Entry(top, width = 30)
        noun3_entry_area.place(x = 210, y = 210)
        adjective4_input_area = Entry(top, width = 30)
        adjective4_input_area.place(x = 210, y = 240)
        noun4_entry_area = Entry(top, width = 30)
        noun4_entry_area.place(x = 210, y = 270)
        adjective5_input_area = Entry(top, width = 30)
        adjective5_input_area.place(x = 210, y = 300)
        noun5_entry_area = Entry(top, width = 30)
        noun5_entry_area.place(x = 210, y = 330)
        adjective6_input_area = Entry(top, width = 30)
        adjective6_input_area.place(x = 210, y = 360)
        noun6_entry_area = Entry(top, width = 30)
        noun6_entry_area.place(x = 210, y = 390)
        adjective7_input_area = Entry(top, width = 30)
        adjective7_input_area.place(x = 210, y = 420)
        adjective8_entry_area = Entry(top, width = 30)
        adjective8_entry_area.place(x = 210, y = 450)
        submit_btn = Button(top, text="Submit", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib(top, adjective1_input_area.get(), noun1_entry_area.get(), adjective2_input_area.get(), noun2_entry_area.get(), adjective3_input_area.get(), noun3_entry_area.get(), adjective4_input_area.get(), noun4_entry_area.get(), adjective5_input_area.get(), noun5_entry_area.get(), adjective6_input_area.get(),noun6_entry_area.get(), adjective7_input_area.get(), adjective8_entry_area.get()))
        submit_btn.place(x=40, y=480)

        top.mainloop()

    def madlib2():
        def finish_madlib2(tl: Toplevel, adjective1, noun1, adjective2, adjective3, noun2, adjective4, noun3, adjective5,  noun4, adjective6, noun5, adjective7, noun6, adjective8, noun7, adjective9, noun8, adjective10):
            text = f'''Once upon a time, a {adjective1} {noun1} set out on a(n) {adjective2} journey. They packed a {adjective3} {noun2} a {adjective4} {noun3} and a {adjective5} {noun4} for the trip. Along the way, they encountered a {adjective6} {noun5} who offered to help. Together, they faced a {adjective7} {noun6} and finally discovered a {adjective8} {noun7}. The {adjective9} {noun8} returned home, proud of their {adjective10} journey.'''
            Label(tl, text='The story:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=600)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=600)

        top = Toplevel(bg='lightblue')
        top.title("The trip")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='The trip - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)
        
        adjective1 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 60) 
        noun1 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 90)
        adjective2 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 120)
        adjective3 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 150)
        noun2 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 180)
        adjective4 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 210)
        noun3 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 240)
        adjective5 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 270)
        noun4 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 300)
        adjective6 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 330)
        noun5 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 360)
        adjective7 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 390)
        noun6 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 420)
        adjective8 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 450)
        noun7 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 480)
        adjective9 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 510)
        noun8 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 540)
        adjective10 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 570)  
        
        adjective1_input_area = Entry(top, width = 30)
        adjective1_input_area.place(x = 210, y = 60) 
        noun1_entry_area = Entry(top, width = 30)
        noun1_entry_area.place(x = 210, y = 90)
        adjective2_input_area = Entry(top, width = 30)
        adjective2_input_area.place(x = 210, y = 120)
        adjective3_entry_area = Entry(top, width = 30)
        adjective3_entry_area.place(x = 210, y = 150)
        noun2_input_area = Entry(top, width = 30)
        noun2_input_area.place(x = 210, y = 180)
        adjective4_entry_area = Entry(top, width = 30)
        adjective4_entry_area.place(x = 210, y = 210)
        noun3_input_area = Entry(top, width = 30)
        noun3_input_area.place(x = 210, y = 240)
        adjective5_entry_area = Entry(top, width = 30)
        adjective5_entry_area.place(x = 210, y = 270)
        noun4_input_area = Entry(top, width = 30)
        noun4_input_area.place(x = 210, y = 300)
        adjective6_entry_area = Entry(top, width = 30)
        adjective6_entry_area.place(x = 210, y = 330)
        noun5_input_area = Entry(top, width = 30)
        noun5_input_area.place(x = 210, y = 360)
        adjective7_entry_area = Entry(top, width = 30)
        adjective7_entry_area.place(x = 210, y = 390)
        noun6_input_area = Entry(top, width = 30)
        noun6_input_area.place(x = 210, y = 420)
        adjective8_entry_area = Entry(top, width = 30)
        adjective8_entry_area.place(x = 210, y = 450)
        noun7_input_area = Entry(top, width = 30)
        noun7_input_area.place(x = 210, y = 480)
        adjective9_entry_area = Entry(top, width = 30)
        adjective9_entry_area.place(x = 210, y = 510)
        noun8_input_area = Entry(top, width = 30)
        noun8_input_area.place(x = 210, y = 540)
        adjective10_entry_area = Entry(top, width = 30)
        adjective10_entry_area.place(x = 210, y = 570)
        submit_btn = Button(top, text="Submit", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib2(top, adjective1_input_area.get(), noun1_entry_area.get(), adjective2_input_area.get(), adjective3_entry_area.get(), noun2_input_area.get(), adjective4_entry_area.get(), noun3_input_area.get(), adjective5_entry_area.get(), noun4_input_area.get(), adjective6_entry_area.get(), noun5_input_area.get(),adjective7_entry_area.get(), noun6_input_area.get(), adjective8_entry_area.get(), noun7_input_area.get(), adjective9_entry_area.get(), noun8_input_area.get(), adjective10_entry_area.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()

    def madlib3():
        def finish_madlib3(tl: Toplevel, animal1, adjective1, body_part1, food1, number1, body_part2, number2, body_part3, adjective2, action, job, adjective3, adjective4, noun1):
            text = f'''The {animal1} is a pet animal. A {animal1} has {adjective1} {body_part1} so that it can eat {food1} very easily, it has {number1} {body_part2} and {number2} {body_part3}. It is a very {adjective2} animal and is very useful in {action} {job}. It runs very {adjective3}, barks {adjective4} and attacks the {noun1}. One can find {animal1}s everywhere in the world.'''
            Label(tl, text='The story:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=500)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=500)

        top = Toplevel(bg='lightblue')
        top.title("Animal")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='Animal - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)
        
        animal1 = Label(top, text = "Enter an animal: ", bg='lightblue').place(x = 40, y = 60) 
        adjective1 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 90)
        body_part1 = Label(top, text = "Enter a body part: ", bg='lightblue').place(x = 40, y = 120)
        food1 = Label(top, text = "Enter a food: ", bg='lightblue').place(x = 40, y = 150)
        number1 = Label(top, text = "Enter a number: ", bg='lightblue').place(x = 40, y = 180)
        body_part2 = Label(top, text = "Enter a body part: ", bg='lightblue').place(x = 40, y = 210)
        number2 = Label(top, text = "Enter a number: ", bg='lightblue').place(x = 40, y = 240)
        body_part3 = Label(top, text = "Enter a body part: ", bg='lightblue').place(x = 40, y = 270)
        adjective2 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 300)
        action = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 330)
        job = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 360)
        adjective3 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 390)
        adjective4 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 420)
        noun1 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 450)
        
        animal1_input_area = Entry(top, width = 30)
        animal1_input_area.place(x = 210, y = 60) 
        adjective1_entry_area = Entry(top, width = 30)
        adjective1_entry_area.place(x = 210, y = 90)
        body_part1_input_area = Entry(top, width = 30)
        body_part1_input_area.place(x = 210, y = 120)
        food1_entry_area = Entry(top, width = 30)
        food1_entry_area.place(x = 210, y = 150)
        number1_input_area = Entry(top, width = 30)
        number1_input_area.place(x = 210, y = 180)
        body_part2_entry_area = Entry(top, width = 30)
        body_part2_entry_area.place(x = 210, y = 210)
        number2_input_area = Entry(top, width = 30)
        number2_input_area.place(x = 210, y = 240)
        body_part3_entry_area = Entry(top, width = 30)
        body_part3_entry_area.place(x = 210, y = 270)
        adjective2_input_area = Entry(top, width = 30)
        adjective2_input_area.place(x = 210, y = 300)
        action_entry_area = Entry(top, width = 30)
        action_entry_area.place(x = 210, y = 330)
        job_input_area = Entry(top, width = 30)
        job_input_area.place(x = 210, y = 360)
        adjective3_entry_area = Entry(top, width = 30)
        adjective3_entry_area.place(x = 210, y = 390)
        adjective4_input_area = Entry(top, width = 30)
        adjective4_input_area.place(x = 210, y = 420)
        noun1_entry_area = Entry(top, width = 30)
        noun1_entry_area.place(x = 210, y = 450)
        submit_btn = Button(top, text="Submit", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib3(top, animal1_input_area.get(), adjective1_entry_area.get(), body_part1_input_area.get(), food1_entry_area.get(), number1_input_area.get(), body_part2_entry_area.get(), number2_input_area.get(), body_part3_entry_area.get(), adjective2_input_area.get(), action_entry_area.get(), job_input_area.get(), adjective3_entry_area.get(), adjective4_input_area.get(), noun1_entry_area.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()

    def madlib4():
        def finish_madlib4(tl: Toplevel, year, country1, nationality1, place1, country2, number):
            text = f'''On December 7, {year}, {country1} launched a surprise aerial attack on the {nationality1} naval base on {place1} Island, {country2}, forcing {country2} to enter World War {number}. The strike climaxed a decade of worsening relations between the {country1} and {country2}.'''
            Label(tl, text='The story:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=500)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=500)

        top = Toplevel(bg='lightblue')
        top.title("War")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='War - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)
        
        year = Label(top, text = "Enter a year: ", bg='lightblue').place(x = 40, y = 60) 
        country1 = Label(top, text = "Enter a country: ", bg='lightblue').place(x = 40, y = 90)
        nationality1 = Label(top, text = "Enter a nationality: ", bg='lightblue').place(x = 40, y = 120)
        place1 = Label(top, text = "Enter a place: ", bg='lightblue').place(x = 40, y = 150)
        country2 = Label(top, text = "Enter a country: ", bg='lightblue').place(x = 40, y = 180)
        number = Label(top, text = "Enter a number: ", bg='lightblue').place(x = 40, y = 210)
        
        year_input_area = Entry(top, width = 30)
        year_input_area.place(x = 210, y = 60) 
        country1_entry_area = Entry(top, width = 30)
        country1_entry_area.place(x = 210, y = 90)
        nationality1_input_area = Entry(top, width = 30)
        nationality1_input_area.place(x = 210, y = 120)
        place1_entry_area = Entry(top, width = 30)
        place1_entry_area.place(x = 210, y = 150)
        country2_input_area = Entry(top, width = 30)
        country2_input_area.place(x = 210, y = 180)
        number_entry_area = Entry(top, width = 30)
        number_entry_area.place(x = 210, y = 210)
        submit_btn = Button(top, text="Submit", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib4(top, year_input_area.get(), country1_entry_area.get(), nationality1_input_area.get(), place1_entry_area.get(), country2_input_area.get(), number_entry_area.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()

    def madlib5():
        def finish_madlib5(tl: Toplevel, adjective1, noun1, noun2, number, adjective2, celebrity, adjective3, verb1, verb2, adjective4):
            text = f'''Formula 1 is my favorite {adjective1} sport. The smell of {noun1} and the sound of {noun2} as the drivers race by at {number} kph is truly {adjective2}. My favorite driver is {celebrity}, who has an incredible {adjective3} and always seems to {verb1} at the right time. I can't wait to see who will {verb2} the {adjective4} trophy this season!'''
            Label(tl, text='The story:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=500)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=500)

        top = Toplevel(bg='lightblue')
        top.title("Formula 1")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='Formula 1 - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)
        
        adjective1 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 60) 
        noun1 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 90)
        noun2 = Label(top, text = "Enter a noun: ", bg='lightblue').place(x = 40, y = 120)
        number = Label(top, text = "Enter a number: ", bg='lightblue').place(x = 40, y = 150)
        adjective2 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 180)
        celebrity = Label(top, text = "Enter a celebrity: ", bg='lightblue').place(x = 40, y = 210)
        adjective3 = Label(top, text = "Enter ana djective: ", bg='lightblue').place(x = 40, y = 240)
        verb1 = Label(top, text = "Enter a verb: ", bg='lightblue').place(x = 40, y = 270)
        verb2 = Label(top, text = "Enter a verb: ", bg='lightblue').place(x = 40, y = 300)
        adjective4 = Label(top, text = "Enter an adjective: ", bg='lightblue').place(x = 40, y = 330)
        
        adjective1_input_area = Entry(top, width = 30)
        adjective1_input_area.place(x = 210, y = 60) 
        noun1_entry_area = Entry(top, width = 30)
        noun1_entry_area.place(x = 210, y = 90)
        noun2_input_area = Entry(top, width = 30)
        noun2_input_area.place(x = 210, y = 120)
        number_entry_area = Entry(top, width = 30)
        number_entry_area.place(x = 210, y = 150)
        adjective2_input_area = Entry(top, width = 30)
        adjective2_input_area.place(x = 210, y = 180)
        celebrity_entry_area = Entry(top, width = 30)
        celebrity_entry_area.place(x = 210, y = 210)
        adjective3_input_area = Entry(top, width = 30)
        adjective3_input_area.place(x = 210, y = 240)
        verb1_entry_area = Entry(top, width = 30)
        verb1_entry_area.place(x = 210, y = 270)
        verb2_input_area = Entry(top, width = 30)
        verb2_input_area.place(x = 210, y = 300)
        adjective4_entry_area = Entry(top, width = 30)
        adjective4_entry_area.place(x = 210, y = 330)
        submit_btn = Button(top, text="Submit", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib5(top, adjective1_input_area.get(), noun1_entry_area.get(), noun2_input_area.get(), number_entry_area.get(), adjective2_input_area.get(), celebrity_entry_area.get(), adjective3_input_area.get(), verb1_entry_area.get(), verb2_input_area.get(), adjective4_entry_area.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()

    Button(root, text= 'The robbery', font ='arial 15', command= madlib1, bg = 'white').place(x=230, y=120)
    Button(root, text= 'The trip', font ='arial 15', command = madlib2, bg = 'white').place(x=245, y=180)
    Button(root, text= 'Animal', font ='arial 15', command = madlib3, bg = 'white').place(x=248, y=240)
    Button(root, text= 'War', font ='arial 15', command = madlib4, bg = 'white').place(x=260, y=300)
    Button(root, text= 'Formula 1', font ='arial 15', command = madlib5, bg = 'white').place(x=235, y=360)
    root.mainloop()
