from tkinter import *


def ger_main():
    root = Tk()
    root.geometry('600x800')
    root.title('Mad Libs Spiel')
    root.resizable(False, False)
    root.configure(bg='lightblue')
    Label(root, text='Mad Libs Spiel\nViel Spaß dabei!', font='arial 20 bold', bg='lightblue').pack()
    Label(root, text='Wähle eine Geschichte aus:', font='arial 15 bold', bg='lightblue').place(x=175, y=80)

    def madlib1():
        def finish_madlib(tl: Toplevel, adjektiv1, nomen1, adjektiv2, nomen2, adjektiv3, nomen3, adjektiv4, nomen4, adjektiv5, nomen5, adjektiv6, nomen6, adjektiv7, adjektiv8):
            text = f'''Heute ging ich in den {adjektiv1} {nomen1} Park mit meinem {adjektiv2} {nomen2}. Wir brachten einige {adjektiv3} {nomen3} und einen {adjektiv4} {nomen4} zum Spielen mit. Während wir spielten, rannte ein {adjektiv5} {nomen5} vorbei und stahl unser {adjektiv6} {nomen6}! Wir jagten ihm nach, aber es war zu {adjektiv7}, um es zu fangen. Trotz des Missgeschicks hatten wir eine {adjektiv8} Zeit im Park und können es kaum erwarten, wieder dorthin zu gehen.'''
            Label(tl, text='Die Geschichte:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=480)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=480)
        top = Toplevel(bg='lightblue')
        top.title("Der Raubüberfall")
        top.geometry('600x600')
        top.resizable(False, False)

        Label(top, text='Der Raubüberfall - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)

        adjektiv1 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=60)
        nomen1 = Label(top, text="Geben Sie ein Nomen ein: ", bg='lightblue').place(x=40, y=90)
        adjektiv2 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=120)
        nomen2 = Label(top, text="Geben Sie ein Nomen ein: ", bg='lightblue').place(x=40, y=150)
        adjektiv3 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=180)
        nomen3 = Label(top, text="Geben Sie ein Nomen ein: ", bg='lightblue').place(x=40, y=210)
        adjektiv4 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=240)
        nomen4 = Label(top, text="Geben Sie ein Nomen ein: ", bg='lightblue').place(x=40, y=270)
        adjektiv5 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=300)
        nomen5 = Label(top, text="Geben Sie ein Nomen ein: ", bg='lightblue').place(x=40, y=330)
        adjektiv6 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=360)
        nomen6 = Label(top, text="Geben Sie ein Nomen ein: ", bg='lightblue').place(x=40, y=390)
        adjektiv7 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=420)
        adjektiv8 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=450)

        adjektiv1_input_area = Entry(top, width=30)
        adjektiv1_input_area.place(x=210, y=60)
        nomen1_input_area = Entry(top, width=30)
        nomen1_input_area.place(x=210, y=90)
        adjektiv2_input_area = Entry(top, width=30)
        adjektiv2_input_area.place(x=210, y=120)
        nomen2_input_area = Entry(top, width=30)
        nomen2_input_area.place(x=210, y=150)
        adjektiv3_input_area = Entry(top, width=30)
        adjektiv3_input_area.place(x=210, y=180)
        nomen3_input_area = Entry(top, width=30)
        nomen3_input_area.place(x=210, y=210)
        adjektiv4_input_area = Entry(top, width=30)
        adjektiv4_input_area.place(x=210, y=240)
        nomen4_input_area = Entry(top, width=30)
        nomen4_input_area.place(x=210, y=270)
        adjektiv5_input_area = Entry(top, width=30)
        adjektiv5_input_area.place(x=210, y=300)
        nomen5_input_area = Entry(top, width=30)
        nomen5_input_area.place(x=210, y=330)
        adjektiv6_input_area = Entry(top, width=30)
        adjektiv6_input_area.place(x=210, y=360)
        nomen6_input_area = Entry(top, width=30)
        nomen6_input_area.place(x=210, y=390)
        adjektiv7_input_area = Entry(top, width=30)
        adjektiv7_input_area.place(x=210, y=420)
        adjektiv8_input_area = Entry(top, width=30)
        adjektiv8_input_area.place(x=210, y=450)
        submit_btn = Button(top, text="Absenden", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib(top, adjektiv1_input_area.get(), nomen1_input_area.get(), adjektiv2_input_area.get(), nomen2_input_area.get(), adjektiv3_input_area.get(), nomen3_input_area.get(), adjektiv4_input_area.get(), nomen4_input_area.get(), adjektiv5_input_area.get(), nomen5_input_area.get(), adjektiv6_input_area.get(), nomen6_input_area.get(), adjektiv7_input_area.get(), adjektiv8_input_area.get()))
        submit_btn.place(x=40, y=480)

        top.mainloop()

    def madlib2():
        def finish_madlib2(tl: Toplevel, adjective1, noun1, adjective2, adjective3, noun2, adjective4, noun3, adjective5, noun4, adjective6, noun5, adjective7, noun6, adjective8, noun7, adjective9, noun8, adjective10):
            text = f'''Es war einmal eine {adjective1} {noun1}, die sich auf eine(n) {adjective2} Reise begab. Sie packte eine {adjective3} {noun2}, ein(e) {adjective4} {noun3} und ein(e) {adjective5} {noun4} für die Reise ein. Unterwegs traf sie auf eine(n) {adjective6} {noun5}, der/die sich anbot zu helfen. Gemeinsam meisterten sie eine(n) {adjective7} {noun6} und entdeckten schließlich eine(n) {adjective8} {noun7}. Die/der {adjective9} {noun8} kehrte stolz von ihrer/seiner {adjective10} Reise zurück.'''
            Label(tl, text='Die Geschichte:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(x=130, y=600)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=600)

        top = Toplevel(bg='lightblue')
        top.title("Die Reise")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='Die Reise - Lückenfüller', font=("Times", 17, 'bold'), bg='lightblue').place(x=115, y=0)

        adjective1 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=60)
        noun1 = Label(top, text="Geben Sie ein Substantiv ein: ", bg='lightblue').place(x=40, y=90)
        adjective2 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=120)
        adjective3 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=150)
        noun2 = Label(top, text="Geben Sie ein Substantiv ein: ", bg='lightblue').place(x=40, y=180)
        adjective4 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=210)
        noun3 = Label(top, text="Geben Sie ein Substantiv ein: ", bg='lightblue').place(x=40, y=240)
        adjective5 = Label(top, text="Geben Sie ein Substantiv ein: ", bg='lightblue').place(x=40, y=270)
        noun4 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=300)
        adjective6 = Label(top, text="Geben Sie ein Substantiv ein: ", bg='lightblue').place(x=40, y=330)
        noun5 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=360)
        adjective7 = Label(top, text="Geben Sie ein Substantiv ein: ", bg='lightblue').place(x=40, y=390)
        noun6 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=420)
        adjective8 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=450)
        noun7 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=480)
        adjective9 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=510)
        noun8 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=540)
        adjective10 = Label(top, text="Geben Sie ein Adjektiv ein: ", bg='lightblue').place(x=40, y=570)

        adjective1_input_area = Entry(top, width=30)
        adjective1_input_area.place(x=210, y=60)
        noun1_entry_area = Entry(top, width=30)
        noun1_entry_area.place(x=210, y=90)
        adjective2_input_area = Entry(top, width=30)
        adjective2_input_area.place(x=210, y=120)
        adjective3_entry_area = Entry(top, width=30)
        adjective3_entry_area.place(x=210, y=150)
        noun2_input_area = Entry(top, width=30)
        noun2_input_area.place(x=210, y=180)
        adjective4_entry_area = Entry(top, width=30)
        adjective4_entry_area.place(x=210, y=210)
        noun3_input_area = Entry(top, width=30)
        noun3_input_area.place(x=210, y=240)
        adjective5_entry_area = Entry(top, width=30)
        adjective5_entry_area.place(x=210, y=270)
        noun4_input_area = Entry(top, width=30)
        noun4_input_area.place(x=210, y=300)
        adjective6_entry_area = Entry(top, width=30)
        adjective6_entry_area.place(x=210, y=330)
        noun5_input_area = Entry(top, width=30)
        noun5_input_area.place(x=210, y=360)
        adjective7_entry_area = Entry(top, width=30)
        adjective7_entry_area.place(x=210, y=390)
        noun6_input_area = Entry(top, width=30)
        noun6_input_area.place(x=210, y=420)
        adjective8_entry_area = Entry(top, width=30)
        adjective8_entry_area.place(x=210, y=450)
        noun7_input_area = Entry(top, width=30)
        noun7_input_area.place(x=210, y=480)
        adjective9_entry_area = Entry(top, width=30)
        adjective9_entry_area.place(x=210, y=510)
        noun8_input_area = Entry(top, width=30)
        noun8_input_area.place(x=210, y=540)
        adjective10_entry_area = Entry(top, width=30)
        adjective10_entry_area.place(x=210, y=570)
        submit_btn = Button(top, text="Absenden", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib2(top, adjective1_input_area.get(), noun1_entry_area.get(), adjective2_input_area.get(), adjective3_entry_area.get(), noun2_input_area.get(), adjective4_entry_area.get(), noun3_input_area.get(), adjective5_entry_area.get(), noun4_input_area.get(), adjective6_entry_area.get(), noun5_input_area.get(), adjective7_entry_area.get(), noun6_input_area.get(), adjective8_entry_area.get(), noun7_input_area.get(), adjective9_entry_area.get(), noun8_input_area.get(), adjective10_entry_area.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()

    def madlib3():
        def finish_madlib3(tl, tier1, adjektiv1, körperteil1, essen1, zahl1, körperteil2, zahl2, körperteil3, adjektiv2, aktion, beruf, adjektiv3, adjektiv4, substantiv1):
            text = f'''Das {tier1} ist ein Haustier. Ein {tier1} hat {adjektiv1}e {körperteil1}, um {essen1} sehr einfach zu fressen. Es hat {zahl1} {körperteil2} und {zahl2} {körperteil3}. Es ist ein sehr {adjektiv2}es Tier und ist sehr nützlich bei {aktion} {beruf}. Es rennt sehr {adjektiv3}, bellt {adjektiv4} und greift das {substantiv1} an. Man kann {tier1} überall auf der Welt finden.'''
            Label(tl, text='Die Geschichte:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
                x=130, y=500)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=500)

        top = Toplevel(bg='lightblue')
        top.title("Tier")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='Tier - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)
        
        tier1 = Label(top, text="Gib ein Tier ein: ", bg='lightblue').place(x=40, y=60) 
        adjektiv1 = Label(top, text="Gib ein Adjektiv ein: ", bg='lightblue').place(x=40, y=90)
        körperteil1 = Label(top, text="Gib ein Körperteil ein: ", bg='lightblue').place(x=40, y=120)
        essen1 = Label(top, text="Gib ein Essen ein: ", bg='lightblue').place(x=40, y=150)
        zahl1 = Label(top, text="Gib eine Zahl ein: ", bg='lightblue').place(x=40, y=180)
        körperteil2 = Label(top, text="Gib ein Körperteil ein: ", bg='lightblue').place(x=40, y=210)
        zahl2 = Label(top, text="Gib eine Zahl ein: ", bg='lightblue').place(x=40, y=240)
        körperteil3 = Label(top, text="Gib ein Körperteil ein: ", bg='lightblue').place(x=40, y=270)
        adjektiv2 = Label(top, text="Gib ein Adjektiv ein: ", bg='lightblue').place(x=40, y=300)
        aktion = Label(top, text="Gib ein Verb ein: ", bg='lightblue').place(x=40, y=330)
        beruf = Label(top, text="Gib ein Beruf ein: ", bg='lightblue').place(x=40, y=360)
        adjektiv3 = Label(top, text="Gib ein Adjektiv ein: ", bg='lightblue').place(x=40, y=390)
        adjektiv4 = Label(top, text="Gib ein Adjektiv ein: ", bg='lightblue').place(x=40, y=420)
        substantiv1 = Label(top, text="Gib ein Substantiv ein: ", bg='lightblue').place(x=40, y=450)
        
        tier1_input_area = Entry(top, width=30)
        tier1_input_area.place(x=210, y=60) 
        adjektiv1_input_area = Entry(top, width=30)
        adjektiv1_input_area.place(x=210, y=90)
        körperteil1_input_area = Entry(top, width=30)
        körperteil1_input_area.place(x=210, y=120)
        essen1_input_area = Entry(top, width=30)
        essen1_input_area.place(x=210, y=150)
        zahl1_input_area = Entry(top, width=30)
        zahl1_input_area.place(x=210, y=180)
        körperteil2_input_area = Entry(top, width=30)
        körperteil2_input_area.place(x=210, y=210)
        zahl2_input_area = Entry(top, width=30)
        zahl2_input_area.place(x=210, y=240)
        körperteil3_input_area = Entry(top, width=30)
        körperteil3_input_area.place(x=210, y=270)
        adjektiv2_input_area = Entry(top, width=30)
        adjektiv2_input_area.place(x=210, y=300)
        aktion_input_area = Entry(top, width=30)
        aktion_input_area.place(x=210, y=330)
        beruf_input_area = Entry(top, width=30)
        beruf_input_area.place(x=210, y=360)
        adjektiv3_input_area = Entry(top, width=30)
        adjektiv3_input_area.place(x=210, y=390)
        adjektiv4_input_area = Entry(top, width=30)
        adjektiv4_input_area.place(x=210, y=420)
        substantiv1_input_area = Entry(top, width=30)
        substantiv1_input_area.place(x=210, y=450)
        
        submit_btn = Button(top, text="Absenden", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib3(top, tier1_input_area.get(), adjektiv1_input_area.get(), körperteil1_input_area.get(), essen1_input_area.get(), zahl1_input_area.get(), körperteil2_input_area.get(), zahl2_input_area.get(), körperteil3_input_area.get(), adjektiv2_input_area.get(), aktion_input_area.get(), beruf_input_area.get(), adjektiv3_input_area.get(), adjektiv4_input_area.get(), substantiv1_input_area.get()))
        submit_btn.place(x=40, y=600)
        
        top.mainloop()

    def madlib4():
        def finish_madlib4(tl: Toplevel, jahr, land1, nationalitaet1, ort1, land2, nummer):
            text = f'''Am 7. Dezember {jahr} startete {land1} einen überraschenden Luftangriff auf die {nationalitaet1} Marinebasis auf der Insel {ort1} in {land2}, was dazu führte, dass {land2} in den Zweiten Weltkrieg eintrat. Der Angriff markierte den Höhepunkt einer zehnjährigen Verschlechterung der Beziehungen zwischen {land1} und {land2}.'''
            Label(tl, text='Die Geschichte:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(x=130, y=500)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=500)

        top = Toplevel(bg='lightblue')
        top.title("Krieg")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='Krieg - Mad Libs', font=("Times", 17, 'bold'), bg='lightblue').place(x=115, y=0)
        
        jahr = Label(top, text="Geben Sie ein Jahr ein: ", bg='lightblue').place(x=40, y=60) 
        land1 = Label(top, text="Geben Sie ein Land ein: ", bg='lightblue').place(x=40, y=90)
        nationalitaet1 = Label(top, text="Geben Sie eine Nationalität ein: ", bg='lightblue').place(x=40, y=120)
        ort1 = Label(top, text="Geben Sie einen Ort ein: ", bg='lightblue').place(x=40, y=150)
        land2 = Label(top, text="Geben Sie ein Land ein: ", bg='lightblue').place(x=40, y=180)
        nummer = Label(top, text="Geben Sie eine Nummer ein: ", bg='lightblue').place(x=40, y=210)
        
        jahr_eingabe = Entry(top, width=30)
        jahr_eingabe.place(x=210, y=60) 
        land1_eingabe = Entry(top, width=30)
        land1_eingabe.place(x=210, y=90)
        nationalitaet1_eingabe = Entry(top, width=30)
        nationalitaet1_eingabe.place(x=210, y=120)
        ort1_eingabe = Entry(top, width=30)
        ort1_eingabe.place(x=210, y=150)
        land2_eingabe = Entry(top, width=30)
        land2_eingabe.place(x=210, y=180)
        nummer_eingabe = Entry(top, width=30)
        nummer_eingabe.place(x=210, y=210)
        submit_btn = Button(top, text="Absenden", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib4(top, jahr_eingabe.get(), land1_eingabe.get(), nationalitaet1_eingabe.get(), ort1_eingabe.get(), land2_eingabe.get(), nummer_eingabe.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()

    def madlib5():
        def finish_madlib5(tl: Toplevel, adjektiv1, nomen1, nomen2, nummer, adjektiv2, prominent, adjektiv3, verb1, verb2, adjektiv4):
            text = f'''Formel 1 ist mein Lieblingssport. Der Geruch von {nomen1} und das Geräusch von {nomen2}, wenn die Fahrer mit {nummer} km/h vorbeirasen, ist wirklich {adjektiv2}. Mein Lieblingsfahrer ist {prominent}, der eine unglaubliche {adjektiv3} hat und immer zur richtigen Zeit {verb1}. Ich kann es kaum erwarten zu sehen, wer in dieser Saison den {adjektiv4} Pokal gewinnt!'''
            Label(tl, text='Die Geschichte:', font=("Times", 13, "bold"), wraplength=tl.winfo_width(), bg='lightblue').place(
            x=130, y=500)
            Label(tl, text=text, font=("Times", 13, 'bold'), wraplength=tl.winfo_width(), bg='lightblue').place(x=0, y=500)

        top = Toplevel(bg='lightblue')
        top.title("Formel 1")
        top.geometry('600x700')
        top.resizable(False, False)

        Label(top, text='Formel 1 - Lückentext', font=("Times", 17, 'bold'), bg='lightblue').place(
            x=115, y=0)

        adjektiv1 = Label(top, text = "Gib ein Adjektiv ein: ", bg='lightblue').place(x = 40, y = 60) 
        nomen1 = Label(top, text = "Gib ein Nomen ein: ", bg='lightblue').place(x = 40, y = 90)
        nomen2 = Label(top, text = "Gib ein Nomen ein: ", bg='lightblue').place(x = 40, y = 120)
        nummer = Label(top, text = "Gib eine Zahl ein: ", bg='lightblue').place(x = 40, y = 150)
        adjektiv2 = Label(top, text = "Gib ein Adjektiv ein: ", bg='lightblue').place(x = 40, y = 180)
        prominent = Label(top, text = "Gib einen Prominenten ein: ", bg='lightblue').place(x = 40, y = 210)
        adjektiv3 = Label(top, text = "Gib ein Adjektiv ein: ", bg='lightblue').place(x = 40, y = 240)
        verb1 = Label(top, text = "Gib ein Verb ein: ", bg='lightblue').place(x = 40, y = 270)
        verb2 = Label(top, text = "Gib ein Verb ein: ", bg='lightblue').place(x = 40, y = 300)
        adjektiv4 = Label(top, text = "Gib ein Adjektiv ein: ", bg='lightblue').place(x = 40, y = 330)

        adjektiv1_input_area = Entry(top, width = 30)
        adjektiv1_input_area.place(x = 210, y = 60) 
        nomen1_input_area = Entry(top, width = 30)
        nomen1_input_area.place(x = 210, y = 90)
        nomen2_input_area = Entry(top, width = 30)
        nomen2_input_area.place(x = 210, y = 120)
        nummer_input_area = Entry(top, width = 30)
        nummer_input_area.place(x = 210, y = 150)
        adjektiv2_input_area = Entry(top, width = 30)
        adjektiv2_input_area.place(x = 210, y = 180)
        prominent_input_area = Entry(top, width = 30)
        prominent_input_area.place(x = 210, y = 210)
        adjektiv3_input_area = Entry(top, width = 30)
        adjektiv3_input_area.place(x = 210, y = 240)
        verb1_input_area = Entry(top, width = 30)
        verb1_input_area.place(x = 210, y = 270)
        verb2_input_area = Entry(top, width = 30)
        verb2_input_area.place(x = 210, y = 300)
        adjektiv4_input_area = Entry(top, width = 30)
        adjektiv4_input_area.place(x = 210, y = 330)

        submit_btn = Button(top, text="Absenden", background="SteelBlue", font=('Times', 12, 'bold'), command=lambda: finish_madlib5(top, adjektiv1_input_area.get(), nomen1_input_area.get(), nomen2_input_area.get(), nummer_input_area.get(), adjektiv2_input_area.get(), prominent_input_area.get(), adjektiv3_input_area.get(), verb1_input_area.get(), verb2_input_area.get(), adjektiv4_input_area.get()))
        submit_btn.place(x=40, y=600)
        top.mainloop()
    
    Button(root, text= 'Der Raubüberfall', font ='arial 15', command= madlib1, bg = 'white').place(x=220, y=120)
    Button(root, text= 'Die Reise', font ='arial 15', command = madlib2, bg = 'white').place(x=250, y=180)
    Button(root, text= 'Tier', font ='arial 15', command = madlib3, bg = 'white').place(x=270, y=240)
    Button(root, text= 'Krieg', font ='arial 15', command = madlib4, bg = 'white').place(x=265, y=300)
    Button(root, text= 'Formel 1', font ='arial 15', command = madlib5, bg = 'white').place(x=250, y=360)
    root.mainloop()